services:
  shortliner-payment:
    build: .
    container_name: shortliner-payment-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env.local
    networks:
      - shortliner-net

networks:
  shortliner-net:
    external: true
